// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoF-ibdgqH-fmUoYogOqey3-iz2s4-sw',
    appId: '1:1092688689311:web:d39082ae3bd192e8630aaa',
    messagingSenderId: '1092688689311',
    projectId: 'health-app-epiqueai',
    authDomain: 'health-app-epiqueai.firebaseapp.com',
    storageBucket: 'health-app-epiqueai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMa9-B56YeZHux4hli2oboYh9ZqsCesU',
    appId: '1:1092688689311:android:03d42be6d24831ac630aaa',
    messagingSenderId: '1092688689311',
    projectId: 'health-app-epiqueai',
    storageBucket: 'health-app-epiqueai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhSwcvenG4lYi95Yg_vz5mGL8rWpSvjU',
    appId: '1:1092688689311:ios:f2f645130403244b630aaa',
    messagingSenderId: '1092688689311',
    projectId: 'health-app-epiqueai',
    storageBucket: 'health-app-epiqueai.firebasestorage.app',
    iosBundleId: 'com.example.aidHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFhSwcvenG4lYi95Yg_vz5mGL8rWpSvjU',
    appId: '1:1092688689311:ios:f2f645130403244b630aaa',
    messagingSenderId: '1092688689311',
    projectId: 'health-app-epiqueai',
    storageBucket: 'health-app-epiqueai.firebasestorage.app',
    iosBundleId: 'com.example.aidHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdoF-ibdgqH-fmUoYogOqey3-iz2s4-sw',
    appId: '1:1092688689311:web:eb608a4bfeb292e6630aaa',
    messagingSenderId: '1092688689311',
    projectId: 'health-app-epiqueai',
    authDomain: 'health-app-epiqueai.firebaseapp.com',
    storageBucket: 'health-app-epiqueai.firebasestorage.app',
  );
}
